Traceback (most recent call last):
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/miniconda3/envs/jbook/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
children = []
pooled_subjects = []
groups = []  # child or adult

for func_file, confound_file, (_, phenotypic) in zip(
        development_dataset.func,
        development_dataset.confounds,
        development_dataset.phenotypic.iterrows()
    ):

    time_series = masker.transform(func_file, confounds=confound_file)
    pooled_subjects.append(time_series)

    if phenotypic['Child_Adult'] == 'child':
        children.append(time_series)

    groups.append(phenotypic['Child_Adult'])

print(f'Data has {len(children)} children.')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 8[0m
[1;32m      2[0m pooled_subjects [38;5;241m=[39m []
[1;32m      3[0m groups [38;5;241m=[39m []  [38;5;66;03m# child or adult[39;00m
[1;32m      5[0m [38;5;28;01mfor[39;00m func_file, confound_file, (_, phenotypic) [38;5;129;01min[39;00m [38;5;28mzip[39m(
[1;32m      6[0m         development_dataset[38;5;241m.[39mfunc,
[1;32m      7[0m         development_dataset[38;5;241m.[39mconfounds,
[0;32m----> 8[0m         [43mdevelopment_dataset[49m[38;5;241;43m.[39;49m[43mphenotypic[49m[38;5;241;43m.[39;49m[43miterrows[49m()
[1;32m      9[0m     ):
[1;32m     11[0m     time_series [38;5;241m=[39m masker[38;5;241m.[39mtransform(func_file, confounds[38;5;241m=[39mconfound_file)
[1;32m     12[0m     pooled_subjects[38;5;241m.[39mappend(time_series)

[0;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'iterrows'

